// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTBPifHK2NwWDEnRe7MXsHfMZXcxdDemA',
    appId: '1:479953758631:web:5dde25b337f628989aae82',
    messagingSenderId: '479953758631',
    projectId: 'driveflutter-798d9',
    authDomain: 'driveflutter-798d9.firebaseapp.com',
    storageBucket: 'driveflutter-798d9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfy-hj7nju5jfKUa3UM1MBMopWry7hnzg',
    appId: '1:479953758631:android:e33070e0806d5f319aae82',
    messagingSenderId: '479953758631',
    projectId: 'driveflutter-798d9',
    storageBucket: 'driveflutter-798d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKsFVKkMYfQ8mnXC2eY_y3YPNB04K5vaw',
    appId: '1:479953758631:ios:3f08dd513a179dc49aae82',
    messagingSenderId: '479953758631',
    projectId: 'driveflutter-798d9',
    storageBucket: 'driveflutter-798d9.firebasestorage.app',
    iosClientId: '479953758631-9t9v0a1cqqjfjmhd71i2fvada973gq7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.driveFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKsFVKkMYfQ8mnXC2eY_y3YPNB04K5vaw',
    appId: '1:479953758631:ios:3f08dd513a179dc49aae82',
    messagingSenderId: '479953758631',
    projectId: 'driveflutter-798d9',
    storageBucket: 'driveflutter-798d9.firebasestorage.app',
    iosClientId: '479953758631-9t9v0a1cqqjfjmhd71i2fvada973gq7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.driveFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTBPifHK2NwWDEnRe7MXsHfMZXcxdDemA',
    appId: '1:479953758631:web:c61936c1331ae5319aae82',
    messagingSenderId: '479953758631',
    projectId: 'driveflutter-798d9',
    authDomain: 'driveflutter-798d9.firebaseapp.com',
    storageBucket: 'driveflutter-798d9.firebasestorage.app',
  );
}
